---
title: "DATA 605: Fundamentals of Computational Mathematics"
author: "Walt Wells, Spring 2017"
subtitle: "Assignment 5"
output:
  html_document:
    css: ../custom.css
    highlight: zenburn
    theme: lumen
---
# Problem 1

In this problem set we'll work out some properties of the least squares solution that we reviewed in the weekly readings. Consider the unsolvable system Ax = b as given below:

$$\begin{bmatrix}1&0\\1&1\\1&3\\1&4\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}=\begin{bmatrix}0\\8\\8\\20\end{bmatrix}$$

* Write R markdown script to compute $A^TA$ and $A^Tb$.
* Solve for $\hat{x}$ in R using the above two computed matrices.
* What is the squared error of this solution?
* Instead of b = [0; 8; 8; 20], start with p = [1; 5; 13; 17] and find the exact solution (i.e. show that this system is solvable as all equations are consistent with each other. This should result in an error vector e = 0).
* Show that the error e = b - p = [-1; 3; -5; 3].
* Show that the error e is orthogonal to p and to each of the columns of A. Your code should be able to print all of the above requested quantities. 

# Problem 2

Consider the modified auto-mpg data (obtained from the UC Irvine Machine Learning dataset). This dataset contains 5 columns: displacement, horsepower, weight, acceleration, mpg. We are going to model mpg as a function of the other four variables.

Write an R markdown script that takes in the auto-mpg data, extracts an A matrix from the first 4 columns and b vector from the fifth (mpg) column. Using the least squares approach, your code should compute the best fitting solution. That is, find the best fitting equation that expresses mpg in terms of the other 4 variables. Finally, calculate the fitting error between the predicted mpg of your model and the actual mpg. Your script should be able to load in the 5 column data set, extract A and b, and perform the rest of the calculations. 

```{r}
auto <- read.table('auto-mpg.data')
names(auto) <- c('displacement', 'horsepower', 'weight', 'acceleration', 'mpg')
A <- auto[,1:4]
b <- auto[,5]

```